
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='danmu-cli',
    version='0.0.1',
    description='Maybe a cross-platform danmu CLI',
    python_requires='>=3.7',
    author='Bruce Zhang',
    author_email='zttt183525594@gmail.com',
    license='AGPL-3.0-only',
    entry_points={"console_scripts": ["danmu-cli = danmu_cli.main:main"]},
    packages=['danmu_cli', 'danmu_cli.presenters', 'danmu_cli.providers', 'danmu_cli.providers.bilibili_content', 'danmu_cli.providers.tars', 'danmu_cli.providers.tars.tars'],
    package_dir={"": "."},
    package_data={"danmu_cli.providers.tars.tars": ["*.tars"]},
    install_requires=['aiohttp==3.*,>=3.7.3', 'click==7.*,>=7.1.2', 'pydantic==1.*,>=1.7.3'],
    extras_require={"dev": ["dephell==0.*,>=0.8.3", "pytest==6.*,>=6.2.2"]},
)
